### ISSUE TITLE
images onto tiles

### ISSUE THREAD

**Issue by hth8** [Gunnar50/SliddingPuzzlePygame#1]
hello, I am trying to figure out how to put images onto tiles in SlidingPuzzlePygame, so when numbers are in right order i can see the full image. But I cant quite think of a way how to do it. 
@Gunnar50 can you help me with that please? 
thanks a lot

**Comment by Gunnar50** [comment]
You will have to cut the image in a image editor first. and then just have to load the images into your project using something like pygame.image.load and assign them to the numbers. In the Tile class, where it says "if text is not empty" instead of creating and drawing the font, just blit the image into the tile.
hope that make sense, let me know if you still stuck and want me to send a code for it.
